ALTER TABLE contract_history DROP CONSTRAINT ck_contract_history_action;

ALTER TABLE contract_history ADD CONSTRAINT ck_contract_history_action CHECK (action IN (
    'CREATE_CONTRACT', 'UPDATE_CONTRACT', 'CHANGE_EXPIRATION_DATE',
    'RENEW_CONTRACT', 'CLOSE_CONTRACT', 'CANCEL_CONTRACT', 'ADD_ASSIGNMENT',
    'REMOVE_ASSIGNMENT', 'NOTIFICATION_SENT', 'NOTIFICATION_FAILED'));
